#!/usr/bin/env bash
# script that securly copys a file to a server, given exactly 4 parameters
if [ "$#" -ne 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

file="$1"
ip="$2"
user="$3"
key="$4"

scp -i "$key" -o StrictHostKeyChecking=no "$file" "$user@$ip:~/"
