#!/usr/bin/env bash
# Configure nginx to redirect '/redirect_me' to youtube using 301

sudo apt update -y
sudo apt install -y nginx

config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
        }
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}
"
echo "Holberton School for the win!" > /var/www/html/index.html
echo "$config" > /etc/nginx/sites-available/default

sudo nginx -t
sudo service nginx restart
