#!/usr/bin/env bash
# Bash script for redirection configuration

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.html

sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

service nginx start
nginx -s reload 2>/dev/null || service nginx restart
