#!/usr/bin/env bash
# Configure nginx with a custom 404 page

set -e

apt-get update
apt-get install -y nginx


echo "Holberton School" > /var/www/html/index.html

echo "Ceci n'est pas une page" > /var/www/html/404.html

cat > /etc/nginx/sites-available/default << 'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;

    location = /404.html {
        internal;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
EOF

nginx -t
service nginx restart
